// Generated with: yarn gen -> cmd/schemaGen.ts

/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface AbstractLogsStorageGetDownloadUrlResponseInterface {
  downloadUrl: string;
}

export interface AbstractLogsStorageGetUploadUrlRequestInterface {
  hostname: string;
  key: string;
  release: string;
  status: 'pending' | 'running' | 'success' | 'failure';
  type: 'init' | 'recipe';
}

export interface AbstractLogsStorageGetUploadUrlResponseInterface {
  storageKey: string;
  uploadUrl: string;
}
