// Generated with: yarn gen -> cmd/schemaGen.ts

/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface RecipeSourceDirInterface {
  path: string;
}
export type RecipeSourceDirInterfaceConfigKey = "dir";
export const RecipeSourceDirInterfaceConfigKeyFirst = "dir";
