# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'npm' # See documentation for possible values
    open-pull-requests-limit: 50
    directory: '/' # Location of package manifests
    schedule:
      interval: 'daily'
    ignore:
      # Pinned because p-limit 4 breaks all the types for some reason
      # https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
      - dependency-name: 'p-limit'
      # Pinned because chalk 5 is ESM
      - dependency-name: 'chalk'
    commit-message:
      prefix: "[npm] "
  - package-ecosystem: docker
    schedule:
      interval: 'daily'
    directory: '/'
    commit-message:
      prefix: "[docker] "
