site_name: kiwi-provider
#strict: true

site_url: https://kiwi.github.io/kiwi-provider/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - toc.integrate
    - content.code.annotate
    - content.code.copy
    - search.suggest
    - search.highlight

dev_addr: 127.0.0.1:8000

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - monorepo
  - mkdocs-simple-hooks:
      hooks:
        on_page_read_source: 'hack.docs.hooks.hooks:on_page_read_source'

nav:
  - Core docs: '!include ./hack/docs/mkdocs.core.yaml'
  - Task modules: '!include ./hack/docs/mkdocs.modules.yaml'
  - Data Sources: '!include ./hack/docs/mkdocs.dataSources.yaml'
  - Host Sources: '!include ./hack/docs/mkdocs.hostSources.yaml'
  - Recipe Sources: '!include ./hack/docs/mkdocs.recipeSources.yaml'
  - Hooks: '!include ./hack/docs/mkdocs.hooks.yaml'
  - Runners: '!include ./hack/docs/mkdocs.runners.yaml'
  - Assets distribution: '!include ./hack/docs/mkdocs.assetsDistribution.yaml'
  - Logs storage: '!include ./hack/docs/mkdocs.logsStorage.yaml'

markdown_extensions:
  - attr_list
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 5
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
