// Generated with: yarn gen -> cmd/schemaGen.ts

/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface ModuleStatFullInterface {
  follow?: false | boolean;
  path: string;
  throw?: false | boolean;
}

export interface ModuleStatInterface {
  follow?: false | boolean;
  path: string;
  throw?: false | boolean;
}
export type ModuleStatInterfaceConfigKey = "stat";
export const ModuleStatInterfaceConfigKeyFirst = "stat";
