// Generated with: yarn gen -> cmd/schemaGen.ts

import { TaskInterface } from '../../components/task.schema.gen';
/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface ModuleSwitchCaseFullInterface {
  fallthrough?: boolean;
  if?: string;
  task?: TaskInterface;
  tasks?: TaskInterface[];
}

export interface ModuleSwitchInterface {
  cases: {
    [x: string]: TaskInterface | TaskInterface[];
  } | ModuleSwitchCaseFullInterface[];
  default?: TaskInterface | TaskInterface[];
  value?: any;
}
export type ModuleSwitchInterfaceConfigKey = "switch";
export const ModuleSwitchInterfaceConfigKeyFirst = "switch";
