// Generated with: yarn gen -> cmd/schemaGen.ts

/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface HostReportRequestInterface {
  hostname: string;
  key: string;
  release: string;
  status: 'pending' | 'running' | 'success' | 'failure';
  timestamp: number;
  type: 'init' | 'recipe';
}
