// Generated with: yarn gen -> cmd/schemaGen.ts

/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface ServerHookInterface {
  /**
   * Unknown Property
   */
  [x: string]: unknown;
  if?: string;
}

export type ServerHookWithArrayInterface = ServerHookInterface | ServerHookInterface[];

export interface ServerListenerInterface {
  addr: "localhost" | string;
  port: 3000 | number;
}

export interface ServerListenerWrapperInterface {
  listener: ServerListenerInterface;
}
