// Generated with: yarn gen -> cmd/schemaGen.ts

/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface RecipeSourceGitInterface {
  cache: true | boolean;
  ref: "master" | string;
  rootPath: "recipes" | string;
  url: string;
}
export type RecipeSourceGitInterfaceConfigKey = "git";
export const RecipeSourceGitInterfaceConfigKeyFirst = "git";
