// Generated with: yarn gen -> cmd/schemaGen.ts

/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface ModuleExitFullInterface {
  message?: string;
  vars?: object;
}

export type ModuleExitInterface = string | ModuleExitFullInterface;
export type ModuleExitInterfaceConfigKey = "exit";
export const ModuleExitInterfaceConfigKeyFirst = "exit";
