// Generated with: yarn gen -> cmd/schemaGen.ts

/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface ModuleTempInterface {
  extension?: string;
  keep?: false | boolean;
  prefix?: string;
}
export type ModuleTempInterfaceConfigKey = "temp";
export const ModuleTempInterfaceConfigKeyFirst = "temp";
