// Generated with: yarn gen -> cmd/schemaGen.ts

/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface ModuleInfoInterface {
  audio?: object;
  baseboard?: object;
  battery?: object;
  bios?: object;
  blockDevices?: object;
  bluetoothDevices?: object;
  chassis?: object;
  cpu?: object;
  cpuCache?: object;
  cpuCurrentSpeed?: object;
  cpuFlags?: object;
  cpuTemperature?: object;
  currentLoad?: object;
  diskLayout?: object;
  disksIO?: object;
  dockerAll?: object;
  dockerContainerProcesses?: {
    id?: string;
  };
  dockerContainerStats?: {
    id?: string;
  };
  dockerContainers?: {
    all?: boolean;
  };
  dockerImages?: {
    all?: boolean;
  };
  dockerInfo?: object;
  dockerVolumes?: object;
  fsOpenFiles?: object;
  fsSize?: {
    drive?: string;
  };
  fsStats?: object;
  fullLoad?: object;
  get?: {
    valuesObject: any;
  };
  getStaticData?: object;
  graphics?: object;
  inetChecksite?: {
    url: string;
  };
  inetLatency?: {
    host?: string;
  };
  mem?: object;
  memLayout?: object;
  networkConnections?: object;
  networkGatewayDefault?: object;
  networkInterfaceDefault?: object;
  networkInterfaces?: object;
  networkStats?: {
    ifaces?: string;
  };
  osInfo?: object;
  printer?: object;
  processLoad?: {
    processNames: string;
  };
  processes?: object;
  services?: {
    serviceName: string;
  };
  shell?: object;
  system?: object;
  usb?: object;
  users?: object;
  uuid?: object;
  vboxInfo?: object;
  versions?: {
    apps?: string;
  };
  wifiConnections?: object;
  wifiInterfaces?: object;
  wifiNetworks?: object;
}
export type ModuleInfoInterfaceConfigKey = "info";
export const ModuleInfoInterfaceConfigKeyFirst = "info";
