// Generated with: yarn gen -> cmd/schemaGen.ts

/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface ModuleExampleInterface {
  hello: string;
}
export type ModuleExampleInterfaceConfigKey = "_example";
export const ModuleExampleInterfaceConfigKeyFirst = "_example";
