// Generated with: yarn gen -> cmd/schemaGen.ts

import { Archive } from '../components/archive';
import { Inventory } from '../components/inventory';
// Generated with: yarn gen -> cmd/schemaGen.ts

import { ArchiveInterface } from '../components/archive.schema.gen';
import { InventoryInterface } from '../components/inventory.schema.gen';
/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface CompileArchiveForHostArgsInterface {
  archive: Archive;
  hostname: string;
  implicitHosts?: string[];
  inventory: Inventory;
}

export interface CompileArchiveForHostResultInterface {
  archive: ArchiveInterface;
  inventory: InventoryInterface;
  stats?: object;
}
