// Generated with: yarn gen -> cmd/schemaGen.ts

/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface AssetsDistributionDirInterface {
  path: string;
}
export type AssetsDistributionDirInterfaceConfigKey = "dir";
export const AssetsDistributionDirInterfaceConfigKeyFirst = "dir";
