// Generated with: yarn gen -> cmd/schemaGen.ts

/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface ModuleFailFullInterface {
  message?: string;
  vars?: object;
}

export type ModuleFailInterface = string | ModuleFailFullInterface;
export type ModuleFailInterfaceConfigKey = "fail";
export const ModuleFailInterfaceConfigKeyFirst = "fail";
