// Generated with: yarn gen -> cmd/schemaGen.ts

/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export type ModuleDebugInterface = any;
export type ModuleDebugInterfaceConfigKey = "debug";
export const ModuleDebugInterfaceConfigKeyFirst = "debug";
