// Generated with: yarn gen -> cmd/schemaGen.ts

/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface HostSourceFileInterface {
  path: string;
  workDir?: string;
}
export type HostSourceFileInterfaceConfigKey = "file";
export const HostSourceFileInterfaceConfigKeyFirst = "file";
