// Generated with: yarn gen -> cmd/schemaGen.ts

/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export type ModuleShellInterface = {
  cmd: string;
  workDir?: string;
} | string;
export type ModuleShellInterfaceConfigKey = "shell";
export const ModuleShellInterfaceConfigKeyFirst = "shell";
