runner:
  docker:
    image: debian:bookworm

tests:
  - name: Test docker container
    tasks:
      # Print details about the running OS
      - shell:
          cmd: |
            cat /etc/os-release
        out: shell

      - test: shell.stdout.includes("Debian GNU/Linux 12 (bookworm)")
