# This example shows how to start a Docker container initialized with systemd
runner:
  docker:
    dockerfile:
      path: files/systemd.Dockerfile

    runArgs:
      - --stop-signal=SIGRTMIN+3
      - --tmpfs
      - /run
      - --tmpfs
      - /run/lock
      # Needed by systemd
      - -v
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

    # The container already comes with systemd,
    # a process that never stops
    sleepCommand: false
    # Before the runner can run tests, we need to make
    # sure systemd is fully booted
    ready:
      command:
        - systemd-notify
        - --booted

tests:
  - name: Test systemd existence
    tasks:
      - name: Check if the system was booted using systemd
        exec:
          - systemd-notify
          - --booted
