// Generated with: yarn gen -> cmd/schemaGen.ts

/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export type ModuleStoreInterface = {
  content: string;
  path: string;
  raw?: boolean;
  workDir?: string;
} | {
  content: any;
  path: string;
  raw?: false;
  workDir?: string;
};
export type ModuleStoreInterfaceConfigKey = "store";
export const ModuleStoreInterfaceConfigKeyFirst = "store";
