// Generated with: yarn gen -> cmd/schemaGen.ts

/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export type ModuleLookPathInterface = string | {
  cmd: string;
  exclude?: string[];
  include?: string[];
};
export type ModuleLookPathInterfaceConfigKey = "lookPath";
export const ModuleLookPathInterfaceConfigKeyFirst = "lookPath";
