// Generated with: yarn gen -> cmd/schemaGen.ts

/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface RecipeSourceWrapperInterface {
  /**
   * Unknown Property
   */
  [x: string]: unknown;
  id?: string;
  skipPropagate?: boolean;
  trusted?: boolean;
  workDir?: string;
}
