// Generated with: yarn gen -> cmd/schemaGen.ts

/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

import { RecipeSourceWrapperInterface } from './recipeSourceWrapper.schema.gen';

export type RecipeSourceListInterface = RecipeSourceWrapperInterface[];
