// Generated with: yarn gen -> cmd/schemaGen.ts

/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface LogsStorageDirInterface {
  path: string;
}
export type LogsStorageDirInterfaceConfigKey = "dir";
export const LogsStorageDirInterfaceConfigKeyFirst = "dir";
