// Generated with: yarn gen -> cmd/schemaGen.ts

/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface DataSourceFileBaseSchema {
  path: string;
  workDir?: string;
}

export interface DataSourceFileFullInterface {
  path: string;
  raw?: boolean;
  workDir?: string;
}

export interface DataSourceFileInterface {
  path: string;
  raw?: boolean;
  workDir?: string;
}

export interface DataSourceFileRawInterface {
  path: string;
  workDir?: string;
}
export type DataSourceFileInterfaceConfigKey = "file";
export const DataSourceFileInterfaceConfigKeyFirst = "file";
export type DataSourceFileRawInterfaceConfigKey = "fileRaw";
export const DataSourceFileRawInterfaceConfigKeyFirst = "fileRaw";
