// Generated with: yarn gen -> cmd/schemaGen.ts

/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface ServerWorkerConfigInterface {
  databasePath: "release.db.txt" | string;
  hostname?: string;
  serverConfigUrl: "http://localhost:3000" | string;
}
