// Generated with: yarn gen -> cmd/schemaGen.ts

import { Recipe } from './recipe';
// Generated with: yarn gen -> cmd/schemaGen.ts

/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

import { RecipeMinimalInterface, RecipeTargetsInterface } from './recipe.schema.gen';

export interface ArchiveInterface {
  recipeSources: {
    [x: string]: ArchiveRecipesMapInterface;
  };
  rootRecipes: ArchiveRecipesMapInterface;
  timestamp: number;
}

export interface ArchiveRecipeEntryInterface {
  assetsArchive?: string;
  config: RecipeMinimalInterface;
  otherHosts?: RecipeTargetsInterface;
  targets?: RecipeTargetsInterface;
}

export interface ArchiveRecipesMapInterface {
  [x: string]: ArchiveRecipeEntryInterface;
}

export interface CreateArchiveArgsInterface {
  archiveDir?: string;
  recipes: Recipe[];
}

export interface RecipeSourceArchiveInterface {
  archive: object;
  dryRun: boolean;
  recipesMap: ArchiveRecipesMapInterface;
  uniqueId: string;
}
export type RecipeSourceArchiveInterfaceConfigKey = "archive";
export const RecipeSourceArchiveInterfaceConfigKeyFirst = "archive";
