// Generated with: yarn gen -> cmd/schemaGen.ts

/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

import { InventoryEntryRelationsInterface } from './inventoryEntry.schema.gen';
import { VarsInterface, VarsSourcesInterface } from './varsContainer.schema.gen';

export interface InventoryGroupInterface {
  pattern?: InventoryGroupStringEntriesInterface;
  relations?: InventoryEntryRelationsInterface;
  vars?: VarsInterface;
  varsKeyRelations?: "__relations" | string;
  varsSources?: VarsSourcesInterface;
}

export interface InventoryGroupSpecialInterface {
  relations?: InventoryEntryRelationsInterface;
  vars?: VarsInterface;
  varsKeyRelations?: "__relations" | string;
  varsSources?: VarsSourcesInterface;
}

export type InventoryGroupStringEntriesInterface = string | string[];

export interface InventoryHostInterface {
  relations?: InventoryEntryRelationsInterface;
  vars?: VarsInterface;
  varsKeyRelations?: "__relations" | string;
  varsSources?: VarsSourcesInterface;
}

export interface InventoryHostSourceInterface {
  /**
   * Unknown Property
   */
  [x: string]: unknown;
}

export interface InventoryInterface {
  groups?: {
    [x: string]: InventoryGroupStringEntriesInterface | InventoryGroupSpecialInterface | InventoryGroupInterface;
  };
  hostSources?: InventoryHostSourceInterface[];
  vars?: VarsInterface;
  varsSources?: VarsSourcesInterface;
}
