// Generated with: yarn gen -> cmd/schemaGen.ts

/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

import { VarsInterface, VarsSourcesInterface } from './varsContainer.schema.gen';

export interface InventoryEntryInterface {
  relations?: InventoryEntryRelationsInterface;
  vars?: VarsInterface;
  varsKeyRelations?: "__relations" | string;
  varsSources?: VarsSourcesInterface;
}

export type InventoryEntryRelationsInterface = string[];
