// Generated with: yarn gen -> cmd/schemaGen.ts

import { RecipeSourceListInterface } from '../recipeSources/recipeSourceList.schema.gen';
import { ModuleRunResultInterface } from '../modules/abstractModuleBase.schema.gen';
/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

import { VarsInterface } from './varsContainer.schema.gen';
import { TaskInterface } from './task.schema.gen';

export interface HostVarsBlockInterface {
  groupVars?: {
    [x: string]: VarsInterface;
  };
  hostVars?: {
    [x: string]: VarsInterface;
  };
}

export interface RecipeDependencyInterface {
  sourceId?: string;
  version?: string;
}

export type RecipeDependencyWithAlternativesInterface = string | null | RecipeDependencyInterface;

export interface RecipeForArchiveInterface {
  config: RecipeMinimalInterface;
  otherHosts?: RecipeTargetsInterface;
  targets?: RecipeTargetsInterface;
}

export interface RecipeInputsInterface {
  [x: string]: 'alternatives' | 'any' | 'array' | 'boolean' | 'date' | 'function' | 'link' | 'number' | 'object' | 'string' | 'symbol' | 'binary' | 'alt' | 'bool' | 'func' | any;
}

export interface RecipeInterface {
  dependencies?: {
    [x: string]: RecipeDependencyWithAlternativesInterface;
  };
  groupVars?: {
    [x: string]: VarsInterface;
  };
  hostVars?: {
    [x: string]: VarsInterface;
  };
  ignoreContextSources?: boolean;
  inputs?: RecipeInputsInterface;
  otherHosts?: RecipeTargetsInterface;
  recipeSources?: RecipeSourceListInterface;
  targets?: RecipeTargetsInterface;
  tasks: TaskInterface[];
  testMocks?: RecipeTestMockInterface[];
  vars?: VarsInterface;
}

export interface RecipeMinimalInterface {
  dependencies?: {
    [x: string]: RecipeDependencyWithAlternativesInterface;
  };
  groupVars?: {
    [x: string]: VarsInterface;
  };
  hostVars?: {
    [x: string]: VarsInterface;
  };
  inputs?: RecipeInputsInterface;
  tasks: TaskInterface[];
  testMocks?: RecipeTestMockInterface[];
  vars?: VarsInterface;
}

export type RecipeTargetsInterface = string[];

export interface RecipeTestMockInterface {
  /**
   * Unknown Property
   */
  [x: string]: unknown;
  result: ModuleRunResultInterface;
}

export interface TestRecipeMinimalInterface {
  dependencies?: {
    [x: string]: RecipeDependencyWithAlternativesInterface;
  };
  groupVars?: {
    [x: string]: VarsInterface;
  };
  hostVars?: {
    [x: string]: VarsInterface;
  };
  inputs?: RecipeInputsInterface;
  tasks: TaskInterface[];
  testMocks?: RecipeTestMockInterface[];
  vars?: VarsInterface;
}
