// Generated with: yarn gen -> cmd/schemaGen.ts

import { ModuleRunResultInterface } from '../modules/abstractModuleBase.schema.gen';
/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

import { VarsInterface } from './varsContainer.schema.gen';
import { ConditionSetInterface } from './testingCommon.schema.gen';

export interface ExitIfFullInterface {
  if: string;
  message?: string;
  vars?: object;
}

export interface FailedIfFullInterface {
  if: string;
  message?: string;
  vars?: object;
}

export interface TaskInterface {
  /**
   * Unknown Property
   */
  [x: string]: unknown;
  exitIf?: string | ExitIfFullInterface;
  failedIf?: string | FailedIfFullInterface;
  if?: string;
  keepPreviousTaskResult?: boolean;
  label?: string;
  out?: string;
  sensitive?: boolean;
  testMocks?: TaskTestMockInterface[];
  vars?: VarsInterface;
}

export interface TaskTestMockInterface {
  if?: ConditionSetInterface;
  result: ModuleRunResultInterface;
}
