// Generated with: yarn gen -> cmd/schemaGen.ts

/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

import { VarsInterface } from './varsContainer.schema.gen';
import { TestMockBaseInterface, TestMockInterface } from './testing.schema.gen';

export interface ExitIfFullInterface {
  if: string;
  message?: string;
  vars?: object;
}

export interface FailIfFullInterface {
  if: string;
  message?: string;
  vars?: object;
}

export interface TaskForArchiveInterface {
  /**
   * Unknown Property
   */
  [x: string]: unknown;
  exitIf?: string | ExitIfFullInterface;
  failIf?: string | FailIfFullInterface;
  if?: string;
  keepPreviousTaskResult?: boolean;
  label?: string;
  out?: string;
  sensitive?: boolean;
  vars?: VarsInterface;
}

export interface TaskInterface {
  /**
   * Unknown Property
   */
  [x: string]: unknown;
  exitIf?: string | ExitIfFullInterface;
  failIf?: string | FailIfFullInterface;
  if?: string;
  ignoreMocks?: boolean;
  keepPreviousTaskResult?: boolean;
  label?: string;
  mock?: TestMockBaseInterface;
  mocks?: TestMockInterface[];
  out?: string;
  sensitive?: boolean;
  vars?: VarsInterface;
}
