// Generated with: yarn gen -> cmd/schemaGen.ts

/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface TestInterface {
  mocks?: TestMockInterface[];
  recipe?: string;
  targets?: string[];
}

export interface TestMockBaseInterface {
  changed?: false | boolean;
  result?: {
    /**
     * Unknown Property
     */
    [x: string]: unknown;
  };
}

export interface TestMockInterface {
  /**
   * Unknown Property
   */
  [x: string]: unknown;
  changed?: false | boolean;
  result?: {
    /**
     * Unknown Property
     */
    [x: string]: unknown;
  };
}
