// Generated with: yarn gen -> cmd/schemaGen.ts

import { ModuleRunResultInterface } from '../modules/abstractModuleBase.schema.gen';
/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export type ConditionSchema = string;

export type ConditionSetInterface = string | string[];

export interface TestMockBaseInterface {
  result: ModuleRunResultInterface;
}
