// Generated with: yarn gen -> cmd/schemaGen.ts

/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

import { VarsSourceInterface } from './varsSource.schema.gen';

export interface VarsContainerInterface {
  vars?: VarsInterface;
  varsSources?: VarsSourcesInterface;
}

export interface VarsInterface {
  /**
   * Unknown Property
   */
  [x: string]: unknown;
}

export type VarsSourcesInterface = VarsSourceInterface[];
