// Generated with: yarn gen -> cmd/schemaGen.ts

/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export type ModuleTestAllConditionsInterface = string | string[] | {
  [x: string]: string;
};

export interface ModuleTestFullInterface {
  silent?: false | boolean;
  tests: ModuleTestAllConditionsInterface;
}

export type ModuleTestInterface = string | string[] | {
  [x: string]: string;
} | ModuleTestFullInterface;

export interface ModuleTestSilentFullInterface {
  tests: ModuleTestAllConditionsInterface;
}

export type ModuleTestSilentInterface = string | string[] | {
  [x: string]: string;
} | ModuleTestSilentFullInterface;
export type ModuleTestInterfaceConfigKey = "test";
export const ModuleTestInterfaceConfigKeyFirst = "test";
export type ModuleTestSilentInterfaceConfigKey = "testSilent";
export const ModuleTestSilentInterfaceConfigKeyFirst = "testSilent";
