// Generated with: yarn gen -> cmd/schemaGen.ts

/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface HostSourceGlobInterface {
  options?: {
    dot?: boolean;
    follow?: boolean;
    ignore?: string | string[];
    magicalBraces?: boolean;
    maxDepth?: number;
  };
  pattern: string | string[];
  workDir?: string;
}
export type HostSourceGlobInterfaceConfigKey = "glob";
export const HostSourceGlobInterfaceConfigKeyFirst = "glob";
