// Generated with: yarn gen -> cmd/schemaGen.ts

import { ServerHookWithArrayInterface } from '../common/server.schema.gen';
import { CompileArchiveForHostResultInterface } from '../../commands/compileArchiveForHost.schema.gen';
/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface AssetsDistributionInterface {
  /**
   * Unknown Property
   */
  [x: string]: unknown;
}

export interface LogsStorageInterface {
  /**
   * Unknown Property
   */
  [x: string]: unknown;
}

export interface ServerConfigConfigInterface {
  archivePath: string;
  assetsDistribution: AssetsDistributionInterface;
  hooks?: ServerConfigHooksInterface;
  inventoryPath: string;
  logsStorage: LogsStorageInterface;
  workDir?: string;
}

export interface ServerConfigHooksInterface {
  report?: ServerHookWithArrayInterface;
}

export type ServerConfigHooksKeysInterface = 'report';

export interface ServerConfigRouteGetConfigForHostnameResultInterface {
  compileResult: CompileArchiveForHostResultInterface;
}
