// Generated with: yarn gen -> cmd/schemaGen.ts

/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export type ModuleExecInterface = {
  args?: string[];
  cmd: string;
  workDir?: string;
} | string | string[];
export type ModuleExecInterfaceConfigKey = "exec";
export const ModuleExecInterfaceConfigKeyFirst = "exec";
