// Generated with: yarn gen -> cmd/schemaGen.ts

/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface RunnerDockerInterface {
  bin?: "docker" | string;
  image: string;
  platform?: 'linux/amd64' | 'linux/arm64' | 'linux/arm/v7' | 'windows/amd64';
  waitCommand?: string[];
}
export type RunnerDockerInterfaceConfigKey = "docker";
export const RunnerDockerInterfaceConfigKeyFirst = "docker";
