// Generated with: yarn gen -> cmd/schemaGen.ts

/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface ModuleRecipeFullInterface {
  id: string;
  sourceId?: string;
  version?: string;
}

export type ModuleRecipeInterface = string | ModuleRecipeFullInterface;
export type ModuleRecipeInterfaceConfigKey = "recipe";
export const ModuleRecipeInterfaceConfigKeyFirst = "recipe";
