// Generated with: yarn gen -> cmd/schemaGen.ts

import { VarsSourceInterface } from '../../components/varsSource.schema.gen';
/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export type ModuleLoadInterface = VarsSourceInterface[] | VarsSourceInterface;
export type ModuleLoadInterfaceConfigKey = "load";
export const ModuleLoadInterfaceConfigKeyFirst = "load";
